### PR TITLE
Fixes color formatting bug. Closes #81.

### LINKED ISSUE #81: When using rgba string in color variable, sometimes the alpha gets removed when rendered.

### PR DESCRIPTION
**Pull request by chriscox**

### CODE REVIEW

File: src/core/variables/ColorVariable.ts [hunk 1]
```diff
@@ -120,4 +120,17 @@ export class ColorVariable extends Variable implements IColorVariableParams {
     variable.title = data.title;
     return variable;
   }
+
+  /**
+   * Returns color value formatted as string if not already.
+   * @override
+   * @param  {any} value The value that should be formatted.
+   * @return {any}       Return either the original or formatted value.
```
Comment (chuga) [inline src/core/variables/ColorVariable.ts]: doesn't ": string" mean that you're returning a string?

**Review by chuga — APPROVED** [review]

File: src/core/variables/ColorVariable.ts (hunk 1 above)
Comment (chriscox) [reply src/core/variables/ColorVariable.ts]: Good catch. Fixed.
