### PR TITLE
Fixes colorVariable bug when changed remotely. Closes #77

### LINKED ISSUE #77: ColorVariable received remotely must be converted to hex.

### PR DESCRIPTION
**Pull request by chriscox**

### CODE REVIEW

File: src/core/variables/ColorVariable.ts [hunk 1]
```diff
@@ -71,6 +71,16 @@ export class ColorVariable extends Variable implements IColorVariableParams {
   }
 
   /**
+   * Updates the selected value.
+   * @override
+   * @param {any} value The selected value.
+   */
+  updateValue(value: any): void {
```
Comment (chuga) [inline src/core/variables/ColorVariable.ts:78]: why not just override the setter for selectedValue? having both a setter for selectedValue and an updateValue is a little confusing imo

Comment (chriscox) [reply src/core/variables/ColorVariable.ts:78]: Yeah its an unfortunate limitation of typescript, that you cannot override a property (or getters/setters), only methods. So as a result I ended up breaking out an additional method that I can override in subclasses.

Comment (chriscox) [reply src/core/variables/ColorVariable.ts:78]: Including an issue tracker with further info regarding this problem:
https://github.com/Microsoft/TypeScript/issues/338

**Review by chuga — APPROVED** [review]
